### ISSUE TITLE
Worms size vergrößern

### ISSUE THREAD

**Issue by SakalAndrej** [Kepplinger/SocketWorms#2]
Hallo,

@Schloemicher wäre es möglich die Worms-Size noch ein wenig zu erhöhen um den Benutzer einen größeren Spaßfaktor zu bieten denn dann würden sich die Skins eine noch größere Rolle zum Spiel beitragen.

Ich hoffe auf eine positive Rückmeldung.

**Comment by Schloemicher** [comment]
Wurden vergrößert.

**Comment by SakalAndrej** [comment]
(Y)
